/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package intento;

/**
 *
 * @author ErickJimz
 */
public class PanelCarrito extends javax.swing.JPanel {
    private double  precioUnitario =45.0;
    /**
     * Creates new form PanelCarrito
     */
    public PanelCarrito() {
        initComponents();
        actualizarInterfaz(Integer.parseInt(lblCantidad.getText().trim()));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        btnSum = new javax.swing.JButton();
        btnRes = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblPrecioTotal = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("Agua embotellada");

        jLabel3.setText("$10.00 c/u");

        lblCantidad.setText("0");

        btnSum.setText("+");
        btnSum.addActionListener(this::btnSumActionPerformed);

        btnRes.setText("-");
        btnRes.addActionListener(this::btnResActionPerformed);

        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Eliminar ");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        lblPrecioTotal.setText("Precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblPrecioTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnSum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRes)))
                .addGap(17, 17, 17)
                .addComponent(jButton3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRes)
                            .addComponent(lblCantidad)
                            .addComponent(btnSum))
                        .addGap(17, 17, 17)
                        .addComponent(lblPrecioTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton3)))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResActionPerformed
        try {
        // 1. Obtenemos el texto actual del JLabel y lo convertimos a número
        int cantidadActual = Integer.parseInt(lblCantidad.getText().trim());
        
        // 2. Validamos: Solo restamos si es mayor que 0 (así nunca será negativo)
        if (cantidadActual > 0) {
            cantidadActual--; // Restamos 1
            
            // 3. Actualizamos el JLabel con el nuevo valor
            lblCantidad.setText(String.valueOf(cantidadActual));
            actualizarInterfaz(cantidadActual);
            // Aquí puedes actualizar también el subtotal si tu objeto 'carrito' lo requiere
        }
    } catch (NumberFormatException e) {
        // Por si el JLabel llega a tener un texto no numérico por error
        lblCantidad.setText("0");
    }
    }//GEN-LAST:event_btnResActionPerformed
    
    private void actualizarInterfaz(int cantidad) {
        // Multiplicamos la cantidad actual por nuestro precio fijo por unidad
        double nuevoPrecioTotal = cantidad * precioUnitario;
        
        // Modificamos los textos visuales en pantalla
        lblCantidad.setText(String.valueOf(cantidad));
        lblPrecioTotal.setText(String.format("$%.2f", nuevoPrecioTotal));
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // 1. Preguntar al usuario si realmente desea eliminar el producto (Buena práctica)
    int respuesta = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Estás seguro de que deseas quitar este producto del carrito?", 
            "Quitar producto", 
            javax.swing.JOptionPane.YES_NO_OPTION
    );
    
    // 2. Si el usuario responde que SÍ
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        
        // Obtenemos el contenedor padre donde está metida toda esta línea/tarjeta
        java.awt.Container padre = this.getParent();
        
        if (padre != null) {
            // Le decimos al padre que elimine de sus componentes a este JComponent (this)
            padre.remove(this);
            
            // CRÍTICO: Obligamos al contenedor a recalcular los espacios y rediseñarse
            padre.revalidate();
            padre.repaint();
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        try {
        // 1. Obtenemos el texto actual del JLabel
        int cantidadActual = Integer.parseInt(lblCantidad.getText().trim());
        
        // 2. Sumamos 1 sin restricciones (o le pones un tope si hay límite de inventario)
        cantidadActual++;
        
        lblCantidad.setText(String.valueOf(cantidadActual));
        actualizarInterfaz(cantidadActual);
        // Aquí también podrías recalcular el precio total de este producto
    } catch (NumberFormatException e) {
        lblCantidad.setText("1");
    }
    }//GEN-LAST:event_btnSumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRes;
    private javax.swing.JButton btnSum;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblPrecioTotal;
    // End of variables declaration//GEN-END:variables
}
