/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intento;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Limon
 */
public class VentanaLogin extends javax.swing.JFrame {
boolean passVisible = false;    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaLogin.class.getName());

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnCrearCuenta = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        lblOlvideUsuario = new javax.swing.JLabel();
        lblOlvideContrasena = new javax.swing.JLabel();
        lblVerContra = new javax.swing.JLabel();
        pwdContraseña1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitulo.setText("Iniciar Sesión");

        lblSubtitulo.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(153, 153, 153));
        lblSubtitulo.setText("Sistema de Ventas Ambulantes");

        txtUsuario.setBackground(new java.awt.Color(221, 221, 221));
        txtUsuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("ingresa tu usuario");
        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);

        btnCrearCuenta.setBackground(new java.awt.Color(204, 204, 204));
        btnCrearCuenta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCrearCuenta.setText("Crear una cuenta");
        btnCrearCuenta.addActionListener(this::btnCrearCuentaActionPerformed);

        btnIniciarSesion.setBackground(new java.awt.Color(51, 51, 255));
        btnIniciarSesion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(this::btnIniciarSesionActionPerformed);

        lblOlvideUsuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblOlvideUsuario.setForeground(new java.awt.Color(51, 51, 255));
        lblOlvideUsuario.setText("olvide mi usuario");

        lblOlvideContrasena.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblOlvideContrasena.setForeground(new java.awt.Color(51, 51, 255));
        lblOlvideContrasena.setText("olvide mi contraseña");
        lblOlvideContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOlvideContrasenaMouseClicked(evt);
            }
        });

        lblVerContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intento/pngwing.com.png"))); // NOI18N
        lblVerContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerContraMouseClicked(evt);
            }
        });

        pwdContraseña1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblSubtitulo))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblTitulo))
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOlvideUsuario)
                            .addComponent(lblOlvideContrasena)))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addComponent(pwdContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVerContra)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtitulo)
                .addGap(42, 42, 42)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOlvideUsuario)
                .addGap(18, 18, 18)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwdContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVerContra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(lblOlvideContrasena)
                .addGap(20, 20, 20)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
    CrearCuenta ventanaRegistro = new CrearCuenta();
    ventanaRegistro.setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
    String userText = txtUsuario.getText().trim();
    String passText = pwdContraseña1.getText().trim(); 
    if (userText.isEmpty() || userText.equals("ingresa tu usuario") || 
        passText.isEmpty() || passText.equals("ingresa tu contraseña")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa tus datos de acceso.");
        return;
    }
    ConexionMySQL mysql = new ConexionMySQL();
    Connection con = mysql.Conectar();
    
    if (con == null) {
        return; 
    }
    String sql = "SELECT Estado FROM usuarios WHERE Usuario = ? AND Contrasena = ?";
    try (PreparedStatement pst = con.prepareStatement(sql)) {
        pst.setString(1, userText);
        pst.setString(2, passText);
        
        try (ResultSet rs = pst.executeQuery()) {
        if (rs.next()) {
        String estado = rs.getString("Estado");
        if (estado.equalsIgnoreCase("Activo")) {
        JOptionPane.showMessageDialog(this, "¡Conexión Exitosa!\nBienvenido al sistema, " + userText);
        VentanaProductos tienda = new VentanaProductos();
        tienda.setVisible(true);
        this.dispose(); 
        } else {
        JOptionPane.showMessageDialog(this, "Esta cuenta se encuentra inactiva.");
        }
        } else {
        JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos. Intenta de nuevo.");
        }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
    } finally {
        try {
            if (con != null) con.close(); 
        } catch (SQLException ex) {
            System.out.println("Error al cerrar conexión: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void lblOlvideContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvideContrasenaMouseClicked
    VentanaRecuperar paso1 = new VentanaRecuperar();
    paso1.setVisible(true);
    this.dispose();  
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOlvideContrasenaMouseClicked

    private void lblVerContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerContraMouseClicked
    if (passVisible) {
            pwdContraseña1.setEchoChar('•'); 
            passVisible = false;
        } else {
            pwdContraseña1.setEchoChar((char) 0);
            passVisible = true;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVerContraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel lblOlvideContrasena;
    private javax.swing.JLabel lblOlvideUsuario;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVerContra;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPasswordField pwdContraseña1;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
