/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intento;

/**
 *
 * @author Limon
 */
public class VentanaTienda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaTienda.class.getName());

    /**
     * Creates new form VentanaTienda
     */
    public VentanaTienda() {
        initComponents();
        btnNavProductos.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
        @Override
        public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(new java.awt.Color(22, 90, 221)); // El azul de tu equipo
            g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 25, 25); // El óvalo
            g2.dispose();
            super.paint(g, c);
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTiendaPrincipal = new javax.swing.JPanel();
        lblTienda = new javax.swing.JLabel();
        btnNavCarrito = new javax.swing.JToggleButton();
        btnNavPedidos = new javax.swing.JToggleButton();
        btnNavProductos = new javax.swing.JToggleButton();
        lblProductosDisponibles = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();
        lblImagen2 = new javax.swing.JLabel();
        lblImagen3 = new javax.swing.JLabel();
        lblImagen4 = new javax.swing.JLabel();
        lblImagen5 = new javax.swing.JLabel();
        lblImagen6 = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblDisponibilidad = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        btnAgregarProducto1 = new javax.swing.JButton();
        lblDisponibilidad1 = new javax.swing.JLabel();
        lblCosto1 = new javax.swing.JLabel();
        lblNombreProducto1 = new javax.swing.JLabel();
        btnAgregarProducto2 = new javax.swing.JButton();
        lblDisponibilidad2 = new javax.swing.JLabel();
        lblCosto2 = new javax.swing.JLabel();
        lblNombreProducto2 = new javax.swing.JLabel();
        btnAgregarProducto3 = new javax.swing.JButton();
        lblDisponibilidad3 = new javax.swing.JLabel();
        lblCosto3 = new javax.swing.JLabel();
        lblNombreProducto3 = new javax.swing.JLabel();
        btnAgregarProducto4 = new javax.swing.JButton();
        lblDisponibilidad4 = new javax.swing.JLabel();
        lblCosto4 = new javax.swing.JLabel();
        lblNombreProducto4 = new javax.swing.JLabel();
        lblNombreProducto5 = new javax.swing.JLabel();
        lblCosto5 = new javax.swing.JLabel();
        lblDisponibilidad5 = new javax.swing.JLabel();
        btnAgregarProducto6 = new javax.swing.JButton();
        btnAgregarProducto8 = new javax.swing.JButton();
        lblDisponibilidad6 = new javax.swing.JLabel();
        lblCosto6 = new javax.swing.JLabel();
        lblNombreProducto6 = new javax.swing.JLabel();
        lblImagen7 = new javax.swing.JLabel();
        lblNombreProducto7 = new javax.swing.JLabel();
        lblCosto7 = new javax.swing.JLabel();
        lblDisponibilidad7 = new javax.swing.JLabel();
        btnAgregarProducto5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTienda.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTienda.setText("Tienda");

        btnNavCarrito.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNavCarrito.setText("Carrito");
        btnNavCarrito.addActionListener(this::btnNavCarritoActionPerformed);

        btnNavPedidos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNavPedidos.setText("mis pedidos");
        btnNavPedidos.addActionListener(this::btnNavPedidosActionPerformed);

        btnNavProductos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNavProductos.setText("Productos");
        btnNavProductos.addActionListener(this::btnNavProductosActionPerformed);

        lblProductosDisponibles.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblProductosDisponibles.setText("Productos disponibles");

        lblImagen.setBackground(new java.awt.Color(255, 255, 51));
        lblImagen.setForeground(new java.awt.Color(153, 0, 0));
        lblImagen.setText("1");

        lblImagen1.setText("2");

        lblImagen2.setText("3");

        lblImagen3.setText("4");

        lblImagen4.setBackground(new java.awt.Color(255, 255, 51));
        lblImagen4.setForeground(new java.awt.Color(153, 0, 0));
        lblImagen4.setText("5");

        lblImagen5.setText("6");

        lblImagen6.setText("7");

        btnAgregarProducto.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregarProducto.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setText("Agregar al carrito");
        btnAgregarProducto.addActionListener(this::btnAgregarProductoActionPerformed);

        btnAgregarProducto1.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregarProducto1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAgregarProducto1.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto1.setText("Agregar al carrito");
        btnAgregarProducto1.addActionListener(this::btnAgregarProducto1ActionPerformed);

        btnAgregarProducto2.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregarProducto2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAgregarProducto2.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto2.setText("Agregar al carrito");
        btnAgregarProducto2.addActionListener(this::btnAgregarProducto2ActionPerformed);

        btnAgregarProducto3.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregarProducto3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAgregarProducto3.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto3.setText("Agregar al carrito");
        btnAgregarProducto3.addActionListener(this::btnAgregarProducto3ActionPerformed);

        btnAgregarProducto4.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregarProducto4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAgregarProducto4.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto4.setText("Agregar al carrito");
        btnAgregarProducto4.addActionListener(this::btnAgregarProducto4ActionPerformed);

        btnAgregarProducto6.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregarProducto6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAgregarProducto6.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto6.setText("Agregar al carrito");
        btnAgregarProducto6.addActionListener(this::btnAgregarProducto6ActionPerformed);

        btnAgregarProducto8.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregarProducto8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAgregarProducto8.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto8.setText("Agregar al carrito");
        btnAgregarProducto8.addActionListener(this::btnAgregarProducto8ActionPerformed);

        lblImagen7.setText("8");

        btnAgregarProducto5.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregarProducto5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAgregarProducto5.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto5.setText("Agregar al carrito");
        btnAgregarProducto5.addActionListener(this::btnAgregarProducto5ActionPerformed);

        javax.swing.GroupLayout panTiendaPrincipalLayout = new javax.swing.GroupLayout(panTiendaPrincipal);
        panTiendaPrincipal.setLayout(panTiendaPrincipalLayout);
        panTiendaPrincipalLayout.setHorizontalGroup(
            panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTiendaPrincipalLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnNavProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(btnNavCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btnNavPedidos)
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTiendaPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panTiendaPrincipalLayout.createSequentialGroup()
                        .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAgregarProducto)
                            .addComponent(lblNombreProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                .addComponent(lblCosto4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDisponibilidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAgregarProducto4)
                            .addComponent(lblImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregarProducto1)
                                    .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                            .addComponent(lblCosto1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblDisponibilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                        .addComponent(lblCosto2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDisponibilidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnAgregarProducto2)
                                    .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                        .addComponent(lblCosto5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDisponibilidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnAgregarProducto6)
                                    .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblImagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNombreProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                        .addComponent(lblCosto6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDisponibilidad6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnAgregarProducto8)
                                    .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblImagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNombreProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panTiendaPrincipalLayout.createSequentialGroup()
                        .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductosDisponibles, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTienda, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(64, 64, 64)
                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarProducto3)
                    .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                        .addComponent(lblCosto3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDisponibilidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombreProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAgregarProducto5)
                    .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                        .addComponent(lblCosto7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDisponibilidad7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNombreProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        panTiendaPrincipalLayout.setVerticalGroup(
            panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTienda)
                .addGap(18, 18, 18)
                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNavCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNavPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNavProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                        .addComponent(lblProductosDisponibles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTiendaPrincipalLayout.createSequentialGroup()
                                .addComponent(lblNombreProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCosto1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisponibilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregarProducto1)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTiendaPrincipalLayout.createSequentialGroup()
                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImagen2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblImagen3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(lblNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDisponibilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAgregarProducto)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                                .addComponent(lblNombreProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lblCosto2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblDisponibilidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAgregarProducto2))
                                            .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                                .addComponent(lblNombreProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lblCosto3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblDisponibilidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAgregarProducto3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))))
                            .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagen6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagen5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                .addComponent(lblNombreProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCosto4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisponibilidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregarProducto4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTiendaPrincipalLayout.createSequentialGroup()
                                .addComponent(lblNombreProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCosto5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisponibilidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregarProducto6))))
                    .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblImagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                .addComponent(lblNombreProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCosto6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisponibilidad6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregarProducto8))
                            .addGroup(panTiendaPrincipalLayout.createSequentialGroup()
                                .addComponent(lblNombreProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panTiendaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCosto7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisponibilidad7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregarProducto5)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(panTiendaPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNavCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNavCarritoActionPerformed

    private void btnNavPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNavPedidosActionPerformed

    private void btnNavProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNavProductosActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnAgregarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProducto1ActionPerformed

    private void btnAgregarProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProducto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProducto2ActionPerformed

    private void btnAgregarProducto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProducto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProducto3ActionPerformed

    private void btnAgregarProducto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProducto4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProducto4ActionPerformed

    private void btnAgregarProducto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProducto6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProducto6ActionPerformed

    private void btnAgregarProducto8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProducto8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProducto8ActionPerformed

    private void btnAgregarProducto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProducto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProducto5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaTienda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnAgregarProducto1;
    private javax.swing.JButton btnAgregarProducto2;
    private javax.swing.JButton btnAgregarProducto3;
    private javax.swing.JButton btnAgregarProducto4;
    private javax.swing.JButton btnAgregarProducto5;
    private javax.swing.JButton btnAgregarProducto6;
    private javax.swing.JButton btnAgregarProducto8;
    private javax.swing.JToggleButton btnNavCarrito;
    private javax.swing.JToggleButton btnNavPedidos;
    private javax.swing.JToggleButton btnNavProductos;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblCosto1;
    private javax.swing.JLabel lblCosto2;
    private javax.swing.JLabel lblCosto3;
    private javax.swing.JLabel lblCosto4;
    private javax.swing.JLabel lblCosto5;
    private javax.swing.JLabel lblCosto6;
    private javax.swing.JLabel lblCosto7;
    private javax.swing.JLabel lblDisponibilidad;
    private javax.swing.JLabel lblDisponibilidad1;
    private javax.swing.JLabel lblDisponibilidad2;
    private javax.swing.JLabel lblDisponibilidad3;
    private javax.swing.JLabel lblDisponibilidad4;
    private javax.swing.JLabel lblDisponibilidad5;
    private javax.swing.JLabel lblDisponibilidad6;
    private javax.swing.JLabel lblDisponibilidad7;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblImagen4;
    private javax.swing.JLabel lblImagen5;
    private javax.swing.JLabel lblImagen6;
    private javax.swing.JLabel lblImagen7;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblNombreProducto1;
    private javax.swing.JLabel lblNombreProducto2;
    private javax.swing.JLabel lblNombreProducto3;
    private javax.swing.JLabel lblNombreProducto4;
    private javax.swing.JLabel lblNombreProducto5;
    private javax.swing.JLabel lblNombreProducto6;
    private javax.swing.JLabel lblNombreProducto7;
    private javax.swing.JLabel lblProductosDisponibles;
    private javax.swing.JLabel lblTienda;
    private javax.swing.JPanel panTiendaPrincipal;
    // End of variables declaration//GEN-END:variables
}
