/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package versionbeta;

import intento.*;


/**
 *
 * @author ErickJimz
 */
public class MenuCarrito extends javax.swing.JPanel {
    private double precioUnitario = 0.0;
    private int stockMaximo = 0;
    private String nombreProducto = "";
    public MenuCarrito() {
        initComponents();
    }
    private int idUsuario;
    private int idProducto;
    public MenuCarrito(int idUsuario, int idProducto, String nombre, double precio, int stock) {
        initComponents();
        this.idUsuario = idUsuario;
        this.idProducto = idProducto;
        this.nombreProducto = nombre;
        this.precioUnitario = precio;
        this.stockMaximo = stock;
        jLabel2.setText(nombre);
        lblPrecio.setText(String.format("$%.2f c/u", precio));
        actualizarInterfaz(1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        btnSum = new javax.swing.JButton();
        btnRes = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        lblPrecioTotal = new javax.swing.JLabel();

        jLabel2.setText("Agua embotellada");

        lblPrecio.setText("$10.00 c/u");

        lblCantidad.setText("0");

        btnSum.setBackground(new java.awt.Color(51, 153, 255));
        btnSum.setForeground(new java.awt.Color(255, 255, 255));
        btnSum.setText("+");
        btnSum.addActionListener(this::btnSumActionPerformed);

        btnRes.setBackground(new java.awt.Color(255, 51, 51));
        btnRes.setForeground(new java.awt.Color(255, 255, 255));
        btnRes.setText("-");
        btnRes.addActionListener(this::btnResActionPerformed);

        btnConfirmar.setForeground(new java.awt.Color(255, 51, 51));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        lblPrecioTotal.setText("Precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblPrecioTotal)
                .addGap(52, 52, 52)
                .addComponent(lblPrecio)
                .addGap(72, 72, 72)
                .addComponent(btnRes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSum)
                .addGap(16, 16, 16)
                .addComponent(btnConfirmar))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirmar)
                            .addComponent(btnSum)
                            .addComponent(lblCantidad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPrecio)
                                .addComponent(lblPrecioTotal))
                            .addComponent(btnRes))))
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResActionPerformed
        try {
            int cantidadActual = Integer.parseInt(lblCantidad.getText().trim());
            if (cantidadActual > 1) {
                cantidadActual--; 
                actualizarInterfaz(cantidadActual);
            }
        } catch (NumberFormatException e) {
            lblCantidad.setText("1");
        }
    }//GEN-LAST:event_btnResActionPerformed
    
    private void actualizarInterfaz(int cantidad) {
     double nuevoPrecioTotal = cantidad * precioUnitario;
        lblCantidad.setText(String.valueOf(cantidad));
        lblPrecioTotal.setText(String.format("$%.2f", nuevoPrecioTotal));
}
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
   int cantidadFinal = Integer.parseInt(lblCantidad.getText().trim());
        ConexionMySQL mysql = new ConexionMySQL();
        java.sql.Connection con = mysql.Conectar();
        if (con != null) {
            String sql = "INSERT INTO carrito (Id_Usuario, Id_Producto, Cantidad) VALUES (?, ?, ?) "
                       + "ON DUPLICATE KEY UPDATE Cantidad = Cantidad + ?";
            try {
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.setInt(1, this.idUsuario);
                pst.setInt(2, this.idProducto);
                pst.setInt(3, cantidadFinal);
                pst.setInt(4, cantidadFinal);
                pst.executeUpdate();
                con.close();
            } catch (Exception e) {
                System.out.println("Error al guardar en carrito: " + e.getMessage());
            }
        }
        javax.swing.JOptionPane.showMessageDialog(this, "¡Agregado al carrito con éxito!");
        java.awt.Container marcoFlotante = javax.swing.SwingUtilities.getAncestorOfClass(javax.swing.JInternalFrame.class, this);
        if (marcoFlotante instanceof javax.swing.JInternalFrame) {
            ((javax.swing.JInternalFrame) marcoFlotante).dispose();
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        try {
            int cantidadActual = Integer.parseInt(lblCantidad.getText().trim());
            if (cantidadActual < stockMaximo) {
                cantidadActual++;
                actualizarInterfaz(cantidadActual);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No puedes agregar más, es todo lo que hay en inventario.");
            }
        } catch (NumberFormatException e) {
            lblCantidad.setText("1");
        }
    }//GEN-LAST:event_btnSumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRes;
    private javax.swing.JButton btnSum;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioTotal;
    // End of variables declaration//GEN-END:variables
}
