/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package versionbeta;

import intento.*;

/**
 *
 * @author ErickJimz
 */
public class VenatanaCarrito extends javax.swing.JInternalFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VenatanaCarrito.class.getName());
    private int idUsuarioActual;
    public VenatanaCarrito() {
        initComponents();
    }
    public VenatanaCarrito(int idUsuario) {
        this.idUsuarioActual = idUsuario;
        initComponents();
        cargarProductosAlCarrito();
    }
public void cargarProductosAlCarrito() {
        String[] columnas = {"Producto", "Vendedor", "Precio", "Cantidad", "Fecha"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false; 
            }
        };
        jTable1.setModel(modelo);

        ConexionMySQL mysql = new ConexionMySQL();
        java.sql.Connection con = mysql.Conectar();
        
        if (con == null) return;

        String sql = "SELECT p.Nombre AS producto, u.Usuario AS vendedor, p.Precio AS precio, c.Cantidad AS cantidad, c.Fecha AS fecha "
                   + "FROM carrito c "
                   + "INNER JOIN productos p ON c.Id_Producto = p.Id_Productos "
                   + "INNER JOIN usuarios u ON p.Id_Usuario = u.Id_Usuario "
                   + "WHERE c.Id_Usuario = ?";

        try {
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, this.idUsuarioActual); 
            java.sql.ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getString("producto");
                fila[1] = rs.getString("vendedor");
                fila[2] = "$" + String.format("%.2f", rs.getDouble("precio")); 
                fila[3] = rs.getInt("cantidad");
                fila[4] = rs.getString("fecha"); 

                modelo.addRow(fila);
            }
            con.close();
        } catch (Exception e) {
            System.out.println("Error al cargar carrito: " + e.getMessage());
        }
        actualizarTotalResumen(); 
    }
public void actualizarTotalResumen() {
        double granTotal = 0.0;
        try {
            for (int i = 0; i < jTable1.getRowCount(); i++) {

                String precioTexto = jTable1.getValueAt(i, 2).toString()
                                            .replace("$", "")
                                            .replace(",", ".")
                                            .trim();
                                            
                int cantidad = Integer.parseInt(jTable1.getValueAt(i, 3).toString());
                granTotal += Double.parseDouble(precioTexto) * cantidad;
            }
        } catch (Exception e) {
            System.out.println("Error al calcular total: " + e.getMessage());
        }
        jLabel7.setText(String.format("$ %.2f", granTotal)); 
        jLabel9.setText(String.format("$ %.2f", granTotal)); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnProductos = new javax.swing.JButton();
        btnCarrito = new javax.swing.JButton();
        btnMisPedidos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnRealizarPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Tienda");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Mi carrito");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 103, -1, -1));

        btnProductos.setBackground(new java.awt.Color(204, 204, 204));
        btnProductos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.addActionListener(this::btnProductosActionPerformed);
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 59, 148, 32));

        btnCarrito.setBackground(new java.awt.Color(204, 204, 204));
        btnCarrito.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCarrito.setText("Carrito");
        btnCarrito.addActionListener(this::btnCarritoActionPerformed);
        jPanel1.add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 59, 148, 32));

        btnMisPedidos.setBackground(new java.awt.Color(204, 204, 204));
        btnMisPedidos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnMisPedidos.setText("Mis Pedidos");
        btnMisPedidos.addActionListener(this::btnMisPedidosActionPerformed);
        jPanel1.add(btnMisPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 59, 148, 32));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Resumen del pedido");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setText("Envio");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, -1));

        jLabel5.setText("Subtotal");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel6.setText("Total");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setText("$ 00.00");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 255, 0));
        jLabel8.setText("Gratis");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel9.setText("$ 00.00");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        btnRealizarPedido.setBackground(new java.awt.Color(51, 51, 255));
        btnRealizarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizarPedido.setText("Realizar Pedido");
        btnRealizarPedido.addActionListener(this::btnRealizarPedidoActionPerformed);
        jPanel2.add(btnRealizarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 190, 280));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Vendedor", "Precio ", "Cantidad", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, 510, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMisPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisPedidosActionPerformed
    javax.swing.JDesktopPane desktop = this.getDesktopPane();
        if (desktop != null) {
            VentanaMisPedidosB misPedidos = new VentanaMisPedidosB(idUsuarioActual);
            desktop.add(misPedidos);
            misPedidos.setSize(this.getSize());
            misPedidos.setLocation(this.getLocation());
            misPedidos.setVisible(true);
            try {
                misPedidos.setSelected(true);
            } catch (Exception e) {}
            this.dispose(); 
        }
    }//GEN-LAST:event_btnMisPedidosActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed

        javax.swing.JDesktopPane desktop = this.getDesktopPane();
        if (desktop != null) {
            VentanaProductosB tienda = new VentanaProductosB(idUsuarioActual);
            desktop.add(tienda);
            tienda.setSize(this.getSize());
            tienda.setLocation(this.getLocation());
            tienda.setVisible(true);
            try {
                tienda.setSelected(true);
            } catch (Exception e) {}
            this.dispose(); 
        }
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPedidoActionPerformed
int filasCarrito = jTable1.getRowCount();
    if (filasCarrito == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Tu carrito está vacío.");
        return;
    }
    ConexionMySQL mysql = new ConexionMySQL();
    java.sql.Connection con = mysql.Conectar();
    if (con != null) {
        try {
            con.setAutoCommit(false);
            String sqlVendedores = "SELECT DISTINCT p.Id_Usuario AS id_vendedor "
                                 + "FROM carrito c "
                                 + "INNER JOIN productos p ON c.Id_Producto = p.Id_Productos "
                                 + "WHERE c.Id_Usuario = ?";
            
            java.sql.PreparedStatement pstVend = con.prepareStatement(sqlVendedores);
            pstVend.setInt(1, this.idUsuarioActual);
            java.sql.ResultSet rsVend = pstVend.executeQuery();
            while (rsVend.next()) {
                int idVendedor = rsVend.getInt("id_vendedor");
                double totalVendedor = 0;
                int cantidadVendedor = 0;
                String sqlItems = "SELECT c.Id_Producto, p.Nombre, c.Cantidad, p.Precio, p.Cantidad AS stock_disponible "
                                + "FROM carrito c "
                                + "INNER JOIN productos p ON c.Id_Producto = p.Id_Productos "
                                + "WHERE c.Id_Usuario = ? AND p.Id_Usuario = ?";
                java.sql.PreparedStatement pstItems = con.prepareStatement(sqlItems);
                pstItems.setInt(1, this.idUsuarioActual);
                pstItems.setInt(2, idVendedor);
                java.sql.ResultSet rsItems = pstItems.executeQuery();
                java.util.List<Object[]> itemsPedido = new java.util.ArrayList<>();
                while (rsItems.next()) {
                int idProd = rsItems.getInt("Id_Producto");
                String nomProd = rsItems.getString("Nombre");
                int cant = rsItems.getInt("Cantidad");
                double prec = rsItems.getDouble("Precio");
                int stock = rsItems.next() ? rsItems.getInt("stock_disponible") : 0; 
                if (cant > stock) {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "¡No se puede realizar el pedido!\n\n" +
                        "El producto '" + nomProd + "' no tiene suficiente stock.\n" +
                        "Disponibles en tienda: " + stock + " arts.\n" +
                        "En tu carrito llevas: " + cant + " arts.\n\n" +
                        "Por favor, reduce la cantidad antes de comprar.", 
                        "Stock Insuficiente", javax.swing.JOptionPane.WARNING_MESSAGE);
                    con.rollback(); 
                    con.close();
                    return; 
                }
    
                totalVendedor += (prec * cant);
                cantidadVendedor += cant;
                itemsPedido.add(new Object[]{idProd, nomProd, cant, prec});
                }
                String sqlPedido = "INSERT INTO pedidos (Id_Usuario, Id_Venta, Estado, Total, Cantidad_Productos, Hora_inicio) VALUES (?, 1, 'En Proceso', ?, ?, NOW())";
                java.sql.PreparedStatement pstPadre = con.prepareStatement(sqlPedido, java.sql.Statement.RETURN_GENERATED_KEYS);
                pstPadre.setInt(1, this.idUsuarioActual); 
                pstPadre.setDouble(2, totalVendedor);
                pstPadre.setInt(3, cantidadVendedor);
                pstPadre.executeUpdate();
                java.sql.ResultSet rsKeys = pstPadre.getGeneratedKeys();
                int idPedidoNuevo = 0;
                if (rsKeys.next()) {
                    idPedidoNuevo = rsKeys.getInt(1);
                }
                String sqlDetalle = "INSERT INTO detalle_pedidos (Id_Pedido, Producto, Cantidad, Precio) VALUES (?, ?, ?, ?)";
                java.sql.PreparedStatement pstHijo = con.prepareStatement(sqlDetalle);
                
                for (Object[] item : itemsPedido) {
                    pstHijo.setInt(1, idPedidoNuevo);
                    pstHijo.setString(2, item[1].toString()); 
                    pstHijo.setInt(3, Integer.parseInt(item[2].toString())); 
                    pstHijo.setDouble(4, Double.parseDouble(item[3].toString())); 
                    pstHijo.executeUpdate();
                }
            }
            String sqlVaciar = "DELETE FROM carrito WHERE Id_Usuario = ?";
            java.sql.PreparedStatement pstBorrar = con.prepareStatement(sqlVaciar);
            pstBorrar.setInt(1, this.idUsuarioActual);
            pstBorrar.executeUpdate();

            con.commit();
            con.close();
            
            javax.swing.JOptionPane.showMessageDialog(this, "¡Tus pedidos se han enviado a los respectivos vendedores con éxito!");
            cargarProductosAlCarrito();

        } catch (Exception e) {
            System.out.println("Error al procesar la compra dividida: " + e.getMessage());
            try { con.rollback(); } catch (Exception ex) {}
        }
      }
    }//GEN-LAST:event_btnRealizarPedidoActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarritoActionPerformed
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VenatanaCarrito().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnMisPedidos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnRealizarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
