/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package versionbeta;

import intento.*;

/**
 *
 * @author ErickJimz
 */
public class VenatanaCarrito extends javax.swing.JInternalFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VenatanaCarrito.class.getName());
    private int idUsuarioActual;

    /**
     * Creates new form carrito
     */
    public VenatanaCarrito() {
        initComponents();
        btnProductos.addActionListener(this::btnProductosActionPerformed);
        cargarProductosAlCarrito();
    }
    public VenatanaCarrito(int idUsuarioActual) {
        this.idUsuarioActual = idUsuarioActual;
        initComponents();
        // 🌟 Amarramos el botón en el constructor con sesión
        btnProductos.addActionListener(this::btnProductosActionPerformed);
        cargarProductosAlCarrito();
    }
public void cargarProductosAlCarrito() {
        String[] columnas = {"Producto", "Vendedor", "Precio", "Cantidad", "Fecha"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false; 
            }
        };
        jTable1.setModel(modelo);

        ConexionMySQL mysql = new ConexionMySQL();
        java.sql.Connection con = mysql.Conectar();
        
        if (con == null) return;

        String sql = "SELECT p.Nombre AS producto, u.Usuario AS vendedor, p.Precio AS precio, c.Cantidad AS cantidad, c.Fecha AS fecha "
                   + "FROM carrito c "
                   + "INNER JOIN productos p ON c.Id_Producto = p.Id_Productos "
                   + "INNER JOIN usuarios u ON p.Id_Usuario = u.Id_Usuario "
                   + "WHERE c.Id_Usuario = ?";

        try {
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, this.idUsuarioActual); 
            java.sql.ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getString("producto");
                fila[1] = rs.getString("vendedor");
                // 💵 Ahora sí podemos mandarlo como String con "$" de forma segura
                fila[2] = "$" + String.format("%.2f", rs.getDouble("precio")); 
                fila[3] = rs.getInt("cantidad");
                fila[4] = rs.getString("fecha"); 

                modelo.addRow(fila);
            }
            con.close();
        } catch (Exception e) {
            System.out.println("Error al cargar carrito: " + e.getMessage());
        }
        actualizarTotalResumen(); 
    }
public void actualizarTotalResumen() {
        double granTotal = 0.0;
        try {
            for (int i = 0; i < jTable1.getRowCount(); i++) {

                String precioTexto = jTable1.getValueAt(i, 2).toString()
                                            .replace("$", "")
                                            .replace(",", ".")
                                            .trim();
                                            
                int cantidad = Integer.parseInt(jTable1.getValueAt(i, 3).toString());
                granTotal += Double.parseDouble(precioTexto) * cantidad;
            }
        } catch (Exception e) {
            System.out.println("Error al calcular total: " + e.getMessage());
        }
        jLabel7.setText(String.format("$ %.2f", granTotal)); 
        jLabel9.setText(String.format("$ %.2f", granTotal)); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnProductos = new javax.swing.JButton();
        btnProductos1 = new javax.swing.JButton();
        btnProductos2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Tienda");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Mi carrito");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 103, -1, -1));

        btnProductos.setBackground(new java.awt.Color(204, 204, 204));
        btnProductos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.addActionListener(this::btnProductosActionPerformed);
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 59, 148, 32));

        btnProductos1.setBackground(new java.awt.Color(204, 204, 204));
        btnProductos1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnProductos1.setText("Carrito");
        jPanel1.add(btnProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 59, 148, 32));

        btnProductos2.setBackground(new java.awt.Color(204, 204, 204));
        btnProductos2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnProductos2.setText("Mis Pedidos");
        btnProductos2.addActionListener(this::btnProductos2ActionPerformed);
        jPanel1.add(btnProductos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 59, 148, 32));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Resumen del pedido");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setText("Envio");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, -1));

        jLabel5.setText("Subtotal");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel6.setText("Total");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setText("$ 00.00");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 255, 0));
        jLabel8.setText("Gratis");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel9.setText("$ 00.00");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Realizar Pedido");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 190, 280));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Vendedor", "Precio ", "Cantidad", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, 510, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductos2ActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed

        javax.swing.JDesktopPane desktop = this.getDesktopPane();
        if (desktop != null) {
            // Instanciamos la tienda pasándole el ID de usuario actual
            VentanaProductosB tienda = new VentanaProductosB(idUsuarioActual);
            desktop.add(tienda);
            tienda.setSize(this.getSize());
            tienda.setLocation(this.getLocation());
            tienda.setVisible(true);
            try {
                tienda.setSelected(true);
            } catch (Exception e) {}
            this.dispose(); 
        }
    }//GEN-LAST:event_btnProductosActionPerformed
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VenatanaCarrito().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProductos1;
    private javax.swing.JButton btnProductos2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
