/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package versionbeta;


import javax.swing.JOptionPane;

/**
 *
 * @author rafhi
 */
public class VentanaProductosB extends javax.swing.JInternalFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaProductosB.class.getName());
 private int idUsuarioActual;
    /**
     * Creates new form VentanaProductos
     */
   public VentanaProductosB() {
    initComponents();

    this.idUsuarioActual = 0;

    prepararVentana();
}

public VentanaProductosB(int idUsuario) {
    initComponents();

    this.idUsuarioActual = idUsuario;

    prepararVentana();
}
private void prepararVentana() {

    marcarBotonActual();

    tblCompras.setCellSelectionEnabled(false);
    tblCompras.setRowSelectionAllowed(true);
    tblCompras.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

    cargarTablaProductos();
}
private void botonActivo(javax.swing.JButton boton) {
    boton.setBackground(new java.awt.Color(36, 107, 255));
    boton.setForeground(java.awt.Color.WHITE);
    boton.setOpaque(true);
    boton.setBorderPainted(false);
}

private void botonInactivo(javax.swing.JButton boton) {
    boton.setBackground(new java.awt.Color(204, 204, 204));
    boton.setForeground(java.awt.Color.BLACK);
    boton.setOpaque(true);
    boton.setBorderPainted(false);
}

private void marcarBotonActual() {
    botonActivo(btnProductos);
    botonInactivo(btnCarrito);
    botonInactivo(btnPedidos);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnProductos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnCarrito = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        btnAgregarCarrito = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Tienda");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 126, 41));

        btnProductos.setBackground(new java.awt.Color(204, 204, 204));
        btnProductos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnProductos.setText("Productos");
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 59, 148, 32));

        btnPedidos.setBackground(new java.awt.Color(204, 204, 204));
        btnPedidos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPedidos.setText("Mis Pedidos");
        jPanel1.add(btnPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 59, 156, 32));

        btnCarrito.setBackground(new java.awt.Color(204, 204, 204));
        btnCarrito.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCarrito.setText("Carrito");
        btnCarrito.addActionListener(this::btnCarritoActionPerformed);
        jPanel1.add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 59, 148, 32));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Productos Disponibles");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, 200, 40));

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del Producto", "Vendedor", "Precio ", "Disponibles ", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCompras.setCellSelectionEnabled(true);
        tblCompras.setShowHorizontalLines(true);
        tblCompras.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblCompras);
        tblCompras.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 149, 739, 379));

        btnAgregarCarrito.setBackground(new java.awt.Color(0, 153, 0));
        btnAgregarCarrito.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAgregarCarrito.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCarrito.setText("Agregar al Carrito");
        btnAgregarCarrito.addActionListener(this::btnAgregarCarritoActionPerformed);
        jPanel1.add(btnAgregarCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 227, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarSesion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 227, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, 40, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
    if (JOptionPane.showConfirmDialog(this, "¿Seguro?") == JOptionPane.YES_OPTION) {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof MyDesktopB) {
            MyDesktopB principal = (MyDesktopB) win;
            principal.mostrarLogin(); 
        }
        this.dispose();
    }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarritoActionPerformed
    int fila = tblCompras.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un producto.");
            return;
        }
        String nombre = tblCompras.getValueAt(fila, 0).toString();
        int disponibles = Integer.parseInt(tblCompras.getValueAt(fila, 3).toString());

        String precioTexto = tblCompras.getValueAt(fila, 2).toString();
        precioTexto = precioTexto.replace("$", "").replace(",", ".").trim();
        double precio = Double.parseDouble(precioTexto);
        int idProducto = 0;
        ConexionMySQL mysql = new ConexionMySQL();
        java.sql.Connection con = mysql.Conectar();
        if (con != null) {
            try {
                String sql = "SELECT Id_Productos FROM productos WHERE Nombre = ?";
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, nombre);
                java.sql.ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    idProducto = rs.getInt("Id_Productos");
                }
                con.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        MenuCarrito panelCarrito = new MenuCarrito(this.idUsuarioActual, idProducto, nombre, precio, disponibles);
        
        javax.swing.JInternalFrame menuFlotante = new javax.swing.JInternalFrame("", false, true, false, false);
        menuFlotante.add(panelCarrito); 
        menuFlotante.setSize(440, 170); 
        
        ((javax.swing.plaf.basic.BasicInternalFrameUI) menuFlotante.getUI()).setNorthPane(null);
        menuFlotante.setBorder(null);

        javax.swing.JDesktopPane desktop = this.getDesktopPane();
        if (desktop != null) {
            desktop.add(menuFlotante);
            menuFlotante.setVisible(true);
            int x = desktop.getWidth() - menuFlotante.getWidth() - 20;
            int y = desktop.getHeight() - menuFlotante.getHeight() - 20;
            menuFlotante.setLocation(x, y);
            try {
                menuFlotante.setSelected(true);
            } catch (Exception e) {}
        }
    }//GEN-LAST:event_btnAgregarCarritoActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
    javax.swing.JDesktopPane desktop = this.getDesktopPane();
        if (desktop != null) {
            VenatanaCarrito carrito = new VenatanaCarrito(idUsuarioActual);
            desktop.add(carrito);
            carrito.setSize(this.getSize());
            carrito.setLocation(this.getLocation());
            
            carrito.setVisible(true);
            try {
                carrito.setSelected(true);
            } catch (Exception e) {}
            
            this.dispose(); 
        }
    }//GEN-LAST:event_btnCarritoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaProductosB().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCarrito;
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCompras;
    // End of variables declaration//GEN-END:variables

public void cargarTablaProductos() {
   String[] columnas = {"Nombre del Producto", "Vendedor", "Precio ", "Disponibles ", "Cantidad"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tblCompras.setModel(modelo);

        ConexionMySQL mysql = new ConexionMySQL();
        java.sql.Connection con = mysql.Conectar();
        
        if (con == null) return;

        String sql = "SELECT p.Nombre AS producto, u.Usuario AS vendedor, p.Precio AS precio, p.Cantidad AS disponibles FROM productos p INNER JOIN usuarios u ON p.Id_Usuario = u.Id_Usuario";

        try {
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getString("producto");
                fila[1] = rs.getString("vendedor");
                fila[2] = "$" + String.format("%.2f", rs.getDouble("precio")); 
                fila[3] = rs.getInt("disponibles");
                fila[4] = 1; 

                modelo.addRow(fila);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}