/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package versionbeta;
import intento.VentanaRecuperar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Limon
 */
public class VentanaLoginB extends javax.swing.JInternalFrame { 
boolean passVisible = false;    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaLoginB.class.getName());
    private MyDesktopB jefe;
   public VentanaLoginB() {
        this.jefe = null;
        initComponents();
    }
    public VentanaLoginB(MyDesktopB principal) {
        this.jefe = principal;
        initComponents();
        
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtUsuario.getText().equals("ingresa tu usuario")) {
                    txtUsuario.setText("");
                    txtUsuario.setForeground(new java.awt.Color(0, 0, 0)); 
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtUsuario.getText().isEmpty()) {
                    txtUsuario.setForeground(new java.awt.Color(153, 153, 153)); 
                    txtUsuario.setText("ingresa tu usuario");
                }
            }
        });
        
        panPrincipal.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnCrearCuenta = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        lblOlvideContrasena = new javax.swing.JLabel();
        lblVerContra = new javax.swing.JLabel();
        pwdContraseña1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 485));

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitulo.setText("Iniciar Sesión");

        lblSubtitulo.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(153, 153, 153));
        lblSubtitulo.setText("Sistema de Ventas Ambulantes");

        txtUsuario.setBackground(new java.awt.Color(221, 221, 221));
        txtUsuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("ingresa tu usuario");
        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);

        btnCrearCuenta.setBackground(new java.awt.Color(204, 204, 204));
        btnCrearCuenta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCrearCuenta.setText("Crear una cuenta");
        btnCrearCuenta.addActionListener(this::btnCrearCuentaActionPerformed);

        btnIniciarSesion.setBackground(new java.awt.Color(51, 51, 255));
        btnIniciarSesion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(this::btnIniciarSesionActionPerformed);

        lblOlvideContrasena.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblOlvideContrasena.setForeground(new java.awt.Color(51, 51, 255));
        lblOlvideContrasena.setText("olvide mi contraseña");
        lblOlvideContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOlvideContrasenaMouseClicked(evt);
            }
        });

        lblVerContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intento/pngwing.com.png"))); // NOI18N
        lblVerContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerContraMouseClicked(evt);
            }
        });

        pwdContraseña1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblSubtitulo))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblTitulo))
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblOlvideContrasena))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addComponent(pwdContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVerContra)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtitulo)
                .addGap(42, 42, 42)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwdContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVerContra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(lblOlvideContrasena)
                .addGap(20, 20, 20)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
    CrearCuentaB ventanaRegistro = new CrearCuentaB(this.jefe);
        if (this.jefe != null) {
            this.jefe.jDesktopPane1.add(ventanaRegistro);
            ventanaRegistro.setSize(420, 560);
            ventanaRegistro.setVisible(true);
            int x = (this.jefe.jDesktopPane1.getWidth() - ventanaRegistro.getWidth()) / 2;
            int y = (this.jefe.jDesktopPane1.getHeight() - ventanaRegistro.getHeight()) / 2;
            ventanaRegistro.setLocation(x, y);
        }
        this.dispose();  
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
    String userText = txtUsuario.getText().trim();
        String passText = pwdContraseña1.getText().trim();
        
        if (userText.isEmpty() || userText.equals("ingresa tu usuario") || 
            passText.isEmpty() || passText.equals("ingresa tu contraseña")) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa tus datos de acceso.");
            return;
        }
        
        ConexionMySQL mysql = new ConexionMySQL();
        Connection con = mysql.Conectar();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "No se pudo establecer comunicación con el servidor.", "Error de red", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        String sql = "SELECT Id_Usuario, Estado, Rol FROM usuarios WHERE Usuario = ? AND Contrasena = ?";
        
        try (PreparedStatement pst = con.prepareStatement(sql)) { // Elminado el 'sql1' fantasma
            pst.setString(1, userText);
            pst.setString(2, passText);
            
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    int idVendedor = rs.getInt("Id_Usuario");
                    String estado = rs.getString("Estado");
                    String rol = rs.getString("Rol"); 
                    
                    if (estado.equalsIgnoreCase("Activo")) {
                        if (rol.equalsIgnoreCase("Administrador")) {
                            JOptionPane.showMessageDialog(this, "¡Bienvenido Administrador, " + userText + "!");
                            versionbeta.VentanaAdministrativoB admin = new versionbeta.VentanaAdministrativoB();
                            
                            if (this.jefe != null) {
                                this.jefe.jDesktopPane1.add(admin); 
                                admin.setVisible(true);
                                int x = (this.jefe.jDesktopPane1.getWidth() - admin.getWidth()) / 2;
                                int y = (this.jefe.jDesktopPane1.getHeight() - admin.getHeight()) / 2;
                                admin.setLocation(x, y);
                            } else {
                                admin.setVisible(true);
                            }
                        } else if (rol.equalsIgnoreCase("Vendedor")) {
                            JOptionPane.showMessageDialog(this, "¡Bienvenido, " + userText + "!");
                            versionbeta.VentanaVentasB ventas = new versionbeta.VentanaVentasB(idVendedor);
                            
                            if (this.jefe != null) {
                                this.jefe.jDesktopPane1.add(ventas); 
                                ventas.setVisible(true);
                                int x = (this.jefe.jDesktopPane1.getWidth() - ventas.getWidth()) / 2;
                                int y = (this.jefe.jDesktopPane1.getHeight() - ventas.getHeight()) / 2;
                                ventas.setLocation(x, y);
                            } else {
                                ventas.setVisible(true);
                            }
                        } else if (rol.equalsIgnoreCase("Cliente")) {
                            JOptionPane.showMessageDialog(this, "¡Bienvenido, " + userText + "!");
                            versionbeta.VentanaProductosB tienda = new versionbeta.VentanaProductosB(idVendedor);
            
                            if (this.jefe != null) {
                                this.jefe.jDesktopPane1.add(tienda); 
                                tienda.setVisible(true);
                                int x = (this.jefe.jDesktopPane1.getWidth() - tienda.getWidth()) / 2;
                                int y = (this.jefe.jDesktopPane1.getHeight() - tienda.getHeight()) / 2;
                                tienda.setLocation(x, y);
                            } else {
                                tienda.setVisible(true);
                            }
            
                            this.dispose(); 
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Esta cuenta se encuentra temporalmente inactiva.", "Acceso denegado", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El usuario o la contraseña no coinciden.", "Datos incorrectos", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un problema al procesar tu solicitud. Inténtalo más tarde.", "Error de sistema", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (con != null) con.close(); 
            } catch (SQLException ex) {
                System.out.println("Error al cerrar conexión: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
   
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void lblOlvideContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvideContrasenaMouseClicked
    javax.swing.JDesktopPane desktop = this.getDesktopPane();
    if (desktop != null) {
        versionbeta.VentanaRecuperarB paso1 = new versionbeta.VentanaRecuperarB();
        desktop.add(paso1);
        paso1.setVisible(true);
        paso1.setSize(470, 310);
        paso1.setLocation((desktop.getWidth() - paso1.getWidth()) / 2, (desktop.getHeight() - paso1.getHeight()) / 2);
    }
    this.dispose();  
    }//GEN-LAST:event_lblOlvideContrasenaMouseClicked

    private void lblVerContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerContraMouseClicked
    if (passVisible) {
            pwdContraseña1.setEchoChar('•'); 
            passVisible = false;
        } else {
            pwdContraseña1.setEchoChar((char) 0);
            passVisible = true;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVerContraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(() -> new VentanaLoginB(null).setVisible(true)); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel lblOlvideContrasena;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVerContra;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPasswordField pwdContraseña1;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
