/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package versionbeta;

import intento.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level; 
import java.util.logging.Logger;

public class VentanaHistorialVentasB extends javax.swing.JInternalFrame {
    
    private Connection cn;
    private PreparedStatement ps;
    private ResultSet rs;
    private int idUsuarioActual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaHistorialVentasB.class.getName());
    public VentanaHistorialVentasB(int idUsuario) {
        this.idUsuarioActual = idUsuario;
        initComponents();
        jTable1.setCellSelectionEnabled(false);
        jTable1.setRowSelectionAllowed(true);
        jTable1.setColumnSelectionAllowed(false);
        cargarPedidos();
    }

    public void cargarPedidos() {
        String[] columnas = {"ID_Pedido", "Comprador", "Productos", "Total", "Estado"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int col) { return false; }
        };
        jTable1.setModel(modelo);

        ConexionMySQL mysql = new ConexionMySQL();
        cn = mysql.Conectar();

        if (cn == null) return;
        String sql = "SELECT p.Id_Pedido, u.Usuario AS Comprador, "
                   + "GROUP_CONCAT(CONCAT(dp.Cantidad, 'x ', dp.Producto) SEPARATOR ', ') AS ListaProductos, "
                   + "p.Total, p.Estado "
                   + "FROM pedidos p "
                   + "INNER JOIN usuarios u ON p.Id_Usuario = u.Id_Usuario "
                   + "INNER JOIN detalle_pedidos dp ON p.Id_Pedido = dp.Id_Pedido "
                   + "INNER JOIN productos pr ON dp.Producto = pr.Nombre "
                   + "WHERE pr.Id_Usuario = ? " 
                   + "GROUP BY p.Id_Pedido "
                   + "ORDER BY p.Id_Pedido DESC";
        try {
            ps = cn.prepareStatement(sql);
            ps.setInt(1, this.idUsuarioActual); 
            rs = ps.executeQuery();
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("Id_Pedido"),
                    rs.getString("Comprador"),
                    rs.getString("ListaProductos"), 
                    "$" + String.format("%.2f", rs.getDouble("Total")),
                    rs.getString("Estado")
                };
                modelo.addRow(fila);
            }
            cn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar pedidos: " + e.getMessage());
        }
        actualizarEstadisticas(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlVentasTotales = new javax.swing.JPanel();
        lblVentasTitulo = new javax.swing.JLabel();
        lblTotalVentas = new javax.swing.JLabel();
        pnlProductosVendidos = new javax.swing.JPanel();
        lblProductosTitulo = new javax.swing.JLabel();
        lblProductosVendidos = new javax.swing.JLabel();
        pnlTransacciones = new javax.swing.JPanel();
        lblTransaccionesTitulo = new javax.swing.JLabel();
        lblTransacciones = new javax.swing.JLabel();
        btnRegistroProductos = new javax.swing.JButton();
        btnHistorialVentas = new javax.swing.JButton();
        btnAceptarPedido = new javax.swing.JButton();
        btnRechazarPedido = new javax.swing.JButton();
        scrollPedidos = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitulo.setText("Historial de Ventas");

        lblVentasTitulo.setText("Ventas Totales");

        lblTotalVentas.setText("175");

        javax.swing.GroupLayout pnlVentasTotalesLayout = new javax.swing.GroupLayout(pnlVentasTotales);
        pnlVentasTotales.setLayout(pnlVentasTotalesLayout);
        pnlVentasTotalesLayout.setHorizontalGroup(
            pnlVentasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasTotalesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlVentasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlVentasTotalesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTotalVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblVentasTitulo))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlVentasTotalesLayout.setVerticalGroup(
            pnlVentasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasTotalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVentasTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblProductosTitulo.setText("Productos vendidos");

        lblProductosVendidos.setText("15");

        javax.swing.GroupLayout pnlProductosVendidosLayout = new javax.swing.GroupLayout(pnlProductosVendidos);
        pnlProductosVendidos.setLayout(pnlProductosVendidosLayout);
        pnlProductosVendidosLayout.setHorizontalGroup(
            pnlProductosVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductosVendidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductosVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductosVendidosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblProductosVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblProductosTitulo))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlProductosVendidosLayout.setVerticalGroup(
            pnlProductosVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductosVendidosLayout.createSequentialGroup()
                .addComponent(lblProductosTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProductosVendidos)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblTransaccionesTitulo.setText("Transacciones");

        lblTransacciones.setText("2");

        javax.swing.GroupLayout pnlTransaccionesLayout = new javax.swing.GroupLayout(pnlTransacciones);
        pnlTransacciones.setLayout(pnlTransaccionesLayout);
        pnlTransaccionesLayout.setHorizontalGroup(
            pnlTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransaccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTransaccionesTitulo)
                    .addComponent(lblTransacciones, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        pnlTransaccionesLayout.setVerticalGroup(
            pnlTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransaccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTransaccionesTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTransacciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegistroProductos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegistroProductos.setText("Registro de Productos");
        btnRegistroProductos.addActionListener(this::btnRegistroProductosActionPerformed);

        btnHistorialVentas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnHistorialVentas.setText("Historial de ventas");
        btnHistorialVentas.addActionListener(this::btnHistorialVentasActionPerformed);

        btnAceptarPedido.setBackground(new java.awt.Color(51, 204, 0));
        btnAceptarPedido.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAceptarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarPedido.setText("Aceptar pedido");
        btnAceptarPedido.addActionListener(this::btnAceptarPedidoActionPerformed);

        btnRechazarPedido.setBackground(new java.awt.Color(255, 0, 0));
        btnRechazarPedido.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRechazarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnRechazarPedido.setText("Rechazar pedido");
        btnRechazarPedido.addActionListener(this::btnRechazarPedidoActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Pedido", "Comprador", "Productos", "Total", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPedidos.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnAceptarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRechazarPedido)
                .addGap(140, 140, 140))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRegistroProductos)
                                .addGap(120, 120, 120)
                                .addComponent(btnHistorialVentas))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnlVentasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(pnlProductosVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlTransacciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(scrollPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTransacciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlVentasTotales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProductosVendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistroProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHistorialVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addComponent(scrollPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarPedido)
                    .addComponent(btnRechazarPedido))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPedidoActionPerformed
    int fila = jTable1.getSelectedRow();
        if (fila == -1) { JOptionPane.showMessageDialog(this, "Selecciona un pedido de la tabla."); return; }

        int idPedido = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        try {
            ConexionMySQL mysql = new ConexionMySQL();
            cn = mysql.Conectar();
            cn.setAutoCommit(false); 
            String sqlStock = "UPDATE productos p JOIN detalle_pedidos dp ON p.Nombre = dp.Producto "
                            + "SET p.Cantidad = p.Cantidad - dp.Cantidad WHERE dp.Id_Pedido = ?";
            ps = cn.prepareStatement(sqlStock);
            ps.setInt(1, idPedido);
            ps.executeUpdate();
            String sqlEstado = "UPDATE pedidos SET Estado = 'ACEPTADO' WHERE Id_Pedido = ?";
            ps = cn.prepareStatement(sqlEstado);
            ps.setInt(1, idPedido);
            ps.executeUpdate();
            cn.commit();
            cn.close();
            JOptionPane.showMessageDialog(this, "¡Pedido aceptado e inventario descontado!");
            cargarPedidos();
        } catch (Exception e) {
            try { cn.rollback(); } catch (Exception ex) {}
            JOptionPane.showMessageDialog(this, "Error al procesar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAceptarPedidoActionPerformed

    private void btnRechazarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechazarPedidoActionPerformed
    int fila = jTable1.getSelectedRow();
        if (fila == -1) { JOptionPane.showMessageDialog(this, "Selecciona un pedido."); return; }

        int idPedido = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        
        try {
            ConexionMySQL mysql = new ConexionMySQL();
            cn = mysql.Conectar();
            String sql = "UPDATE pedidos SET Estado = 'RECHAZADO' WHERE Id_Pedido = ?";
            ps = cn.prepareStatement(sql);
            ps.setInt(1, idPedido);
            ps.executeUpdate();
            cn.close();
            
            cargarPedidos();
            JOptionPane.showMessageDialog(this, "Pedido rechazado.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRechazarPedidoActionPerformed

    private void btnRegistroProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroProductosActionPerformed

    javax.swing.JDesktopPane desktop = this.getDesktopPane();
    if (desktop != null) {
        versionbeta.VentanaVentasB productos = new versionbeta.VentanaVentasB(this.idUsuarioActual);
        desktop.add(productos);
        productos.setVisible(true);
        int x = (desktop.getWidth() - productos.getWidth()) / 2;
        int y = (desktop.getHeight() - productos.getHeight()) / 2;
        productos.setLocation(x, y);
        this.dispose();
    }
    }//GEN-LAST:event_btnRegistroProductosActionPerformed

    private void btnHistorialVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialVentasActionPerformed

    }//GEN-LAST:event_btnHistorialVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> new VentanaHistorialVentasB(0).setVisible(true));
    }
    public void actualizarEstadisticas() {
    ConexionMySQL mysql = new ConexionMySQL();
    java.sql.Connection con = mysql.Conectar();
    if (con == null) return;
    String sqlVentas = "SELECT IFNULL(SUM(sub.Total), 0) AS total_dinero FROM (SELECT DISTINCT p.Id_Pedido, p.Total FROM pedidos p INNER JOIN detalle_pedidos dp ON p.Id_Pedido = dp.Id_Pedido INNER JOIN productos pr ON dp.Producto = pr.Nombre WHERE pr.Id_Usuario = ? AND p.Estado = 'ACEPTADO') AS sub";
    String sqlProds = "SELECT IFNULL(SUM(dp.Cantidad), 0) AS total_articulos FROM detalle_pedidos dp INNER JOIN pedidos p ON dp.Id_Pedido = p.Id_Pedido INNER JOIN productos pr ON dp.Producto = pr.Nombre WHERE pr.Id_Usuario = ? AND p.Estado = 'ACEPTADO'";
    String sqlTrans = "SELECT COUNT(DISTINCT p.Id_Usuario) AS total_clientes FROM pedidos p INNER JOIN detalle_pedidos dp ON p.Id_Pedido = dp.Id_Pedido INNER JOIN productos pr ON dp.Producto = pr.Nombre WHERE pr.Id_Usuario = ? AND p.Estado = 'ACEPTADO'";

    try {
        java.sql.PreparedStatement ps1 = con.prepareStatement(sqlVentas);
        ps1.setInt(1, this.idUsuarioActual);
        java.sql.ResultSet rs1 = ps1.executeQuery();
        if (rs1.next()) {
            lblTotalVentas.setText(String.format("$ %.2f", rs1.getDouble("total_dinero")));
        }
        java.sql.PreparedStatement ps2 = con.prepareStatement(sqlProds);
        ps2.setInt(1, this.idUsuarioActual);
        java.sql.ResultSet rs2 = ps2.executeQuery();
        if (rs2.next()) {
            lblProductosVendidos.setText(rs2.getInt("total_articulos")+" arts.");
        }
        java.sql.PreparedStatement ps3 = con.prepareStatement(sqlTrans);
        ps3.setInt(1, this.idUsuarioActual);
        java.sql.ResultSet rs3 = ps3.executeQuery();
        if (rs3.next()) {
            lblTransacciones.setText(String.valueOf(rs3.getInt("total_clientes")));
        }
        con.close();
    } catch (Exception e) {
        System.out.println("Error al actualizar estadísticas de historial: " + e.getMessage());
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarPedido;
    private javax.swing.JButton btnHistorialVentas;
    private javax.swing.JButton btnRechazarPedido;
    private javax.swing.JButton btnRegistroProductos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblProductosTitulo;
    private javax.swing.JLabel lblProductosVendidos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalVentas;
    private javax.swing.JLabel lblTransacciones;
    private javax.swing.JLabel lblTransaccionesTitulo;
    private javax.swing.JLabel lblVentasTitulo;
    private javax.swing.JPanel pnlProductosVendidos;
    private javax.swing.JPanel pnlTransacciones;
    private javax.swing.JPanel pnlVentasTotales;
    private javax.swing.JScrollPane scrollPedidos;
    // End of variables declaration//GEN-END:variables
}


